[package]
name = "kolekk"
version = "0.1.0"
edition = "2021"
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2.2", features = ["api-all"] }
anyhow = "1.0.68"
ts-rs = "6.2.1"
tauri-specta = "0.0.2"
# lib-mal = "0.5.1"
lib-mal = { path="./crates/lib-mal" } # has a super stupid bug
tokio = { version = "1", features = ["full"] }
sea-orm = { version = "0.10.7", features = [ "sqlx-sqlite", "runtime-tokio-native-tls", "macros" ] }

[dependencies.musiplayer]
# version = "0.1"
path = "../../musimanager/musiplayer"


[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
