
[workspace]
members = [
  "src-tauri",
  "src-tauri/crates/*",
]
resolver = "2"

default-members = [
  "src-tauri"
]

# enable optimised compiling for libraries even in debug builds
# [profile.dev.package."*"]
[profile.dev.package."image"]
opt-level = 3

[profile.release]
incremental = true
